DROP TABLE IF EXISTS tb_instituicao;

CREATE TABLE tb_instituicao (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NO_REGIAO TEXT,
    CO_REGIAO INTEGER,
    NO_UF TEXT,
    CO_UF INTEGER,
    NO_MUNICIPIO TEXT,
    CO_MUNICIPIO INTEGER,
    NO_MESORREGIAO TEXT,
    CO_MESORREGIAO INTEGER,
    NO_MICRORREGIAO TEXT,
    CO_MICRORREGIAO INTEGER,
    NO_ENTIDADE TEXT,
    CO_ENTIDADE INTEGER,
    QT_MAT_BAS INTEGER,
    QT_MAT_INF INTEGER,
    QT_MAT_FUND INTEGER,
    QT_MAT_MED INTEGER,
    QT_MAT_EJA INTEGER,
    QT_MAT_ESP INTEGER
);