"""primeira migração

Revision ID: d9348fad2a49
Revises: 
Create Date: 2025-08-11 19:15:33.150996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9348fad2a49'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_instituicao', schema=None) as batch_op:
       #  batch_op.alter_column('id',
       #         existing_type=sa.INTEGER(),
       #         server_default=None,
       #         existing_nullable=False,
       #         autoincrement=True)
        batch_op.alter_column('no_regiao',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('no_entidade',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('tb_mesorregiao', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('tb_microrregiao', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('tb_municipio', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('tb_uf', schema=None) as batch_op:
        batch_op.alter_column('sigla',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('nome',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_uf', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('sigla',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('tb_municipio', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('tb_microrregiao', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('tb_mesorregiao', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('tb_instituicao', schema=None) as batch_op:
        batch_op.alter_column('no_entidade',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('no_regiao',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
