from marshmallow import Schema, fields

class InstituicaoEnsino():
    def __init__(self, **kwargs):
        self.id = kwargs.get('id')
        self.NO_REGIAO = kwargs.get('NO_REGIAO')
        self.CO_REGIAO = kwargs.get('CO_REGIAO')
        self.NO_UF = kwargs.get('NO_UF')
        self.CO_UF = kwargs.get('CO_UF')
        self.NO_MUNICIPIO = kwargs.get('NO_MUNICIPIO')
        self.CO_MUNICIPIO = kwargs.get('CO_MUNICIPIO')
        self.NO_MESORREGIAO = kwargs.get('NO_MESORREGIAO')
        self.CO_MESORREGIAO = kwargs.get('CO_MESORREGIAO')
        self.NO_MICRORREGIAO = kwargs.get('NO_MICRORREGIAO')
        self.CO_MICRORREGIAO = kwargs.get('CO_MICRORREGIAO')
        self.NO_ENTIDADE = kwargs.get('NO_ENTIDADE')
        self.CO_ENTIDADE = kwargs.get('CO_ENTIDADE')
        self.QT_MAT_BAS = kwargs.get('QT_MAT_BAS')
        self.QT_MAT_INF = kwargs.get('QT_MAT_INF')
        self.QT_MAT_FUND = kwargs.get('QT_MAT_FUND')
        self.QT_MAT_MED = kwargs.get('QT_MAT_MED')
        self.QT_MAT_EJA = kwargs.get('QT_MAT_EJA')
        self.QT_MAT_ESP = kwargs.get('QT_MAT_ESP')
        
class InstituicaoEnsinoSchema(Schema):
    id = fields.Int()
    NO_REGIAO = fields.Str()
    CO_REGIAO = fields.Int()
    NO_UF = fields.Str()
    CO_UF = fields.Int()
    NO_MUNICIPIO = fields.Str()
    CO_MUNICIPIO = fields.Int()
    NO_MESORREGIAO = fields.Str()
    CO_MESORREGIAO = fields.Int()
    NO_MICRORREGIAO = fields.Str()
    CO_MICRORREGIAO = fields.Int()
    NO_ENTIDADE = fields.Str()
    CO_ENTIDADE = fields.Int()
    QT_MAT_BAS = fields.Int()
    QT_MAT_INF = fields.Int()
    QT_MAT_FUND = fields.Int()
    QT_MAT_MED = fields.Int()
    QT_MAT_EJA = fields.Int()
    QT_MAT_ESP = fields.Int()